package com.ktfootball.www.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GAMES.
 */
public class Games {

    private Long id;
    private String game_id;
    private String game_enter_users_count;
    private String name;
    private String time_start;
    private String time_end;
    private String avatar;
    private String introduction;
    private String location;
    private String ktb;
    private String enter_time_start;
    private String enter_time_end;
    private String place;
    private String country;
    private String city;

    public Games() {
    }

    public Games(Long id) {
        this.id = id;
    }

    public Games(Long id, String game_id, String game_enter_users_count, String name, String time_start, String time_end, String avatar, String introduction, String location, String ktb, String enter_time_start, String enter_time_end, String place, String country, String city) {
        this.id = id;
        this.game_id = game_id;
        this.game_enter_users_count = game_enter_users_count;
        this.name = name;
        this.time_start = time_start;
        this.time_end = time_end;
        this.avatar = avatar;
        this.introduction = introduction;
        this.location = location;
        this.ktb = ktb;
        this.enter_time_start = enter_time_start;
        this.enter_time_end = enter_time_end;
        this.place = place;
        this.country = country;
        this.city = city;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGame_id() {
        return game_id;
    }

    public void setGame_id(String game_id) {
        this.game_id = game_id;
    }

    public String getGame_enter_users_count() {
        return game_enter_users_count;
    }

    public void setGame_enter_users_count(String game_enter_users_count) {
        this.game_enter_users_count = game_enter_users_count;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTime_start() {
        return time_start;
    }

    public void setTime_start(String time_start) {
        this.time_start = time_start;
    }

    public String getTime_end() {
        return time_end;
    }

    public void setTime_end(String time_end) {
        this.time_end = time_end;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getKtb() {
        return ktb;
    }

    public void setKtb(String ktb) {
        this.ktb = ktb;
    }

    public String getEnter_time_start() {
        return enter_time_start;
    }

    public void setEnter_time_start(String enter_time_start) {
        this.enter_time_start = enter_time_start;
    }

    public String getEnter_time_end() {
        return enter_time_end;
    }

    public void setEnter_time_end(String enter_time_end) {
        this.enter_time_end = enter_time_end;
    }

    public String getPlace() {
        return place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

}
