package com.ktfootball.www.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RANKING_LEAGUE_SCORES3V3.
 */
public class RankingLeagueScores3v3 {

    private Long id;
    private String league_id;
    private String name;
    private String scores;
    private String win_rate;

    public RankingLeagueScores3v3() {
    }

    public RankingLeagueScores3v3(Long id) {
        this.id = id;
    }

    public RankingLeagueScores3v3(Long id, String league_id, String name, String scores, String win_rate) {
        this.id = id;
        this.league_id = league_id;
        this.name = name;
        this.scores = scores;
        this.win_rate = win_rate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLeague_id() {
        return league_id;
    }

    public void setLeague_id(String league_id) {
        this.league_id = league_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getScores() {
        return scores;
    }

    public void setScores(String scores) {
        this.scores = scores;
    }

    public String getWin_rate() {
        return win_rate;
    }

    public void setWin_rate(String win_rate) {
        this.win_rate = win_rate;
    }

}
