package com.ktfootball.www.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RANKING_POWER.
 */
public class RankingPower {

    private Long id;
    private String user_id;
    private String nickname;
    private String age;
    private String gender;
    private String school_grade;
    private String school_cls;
    private String scores;
    private String power;
    private String win_rate;

    public RankingPower() {
    }

    public RankingPower(Long id) {
        this.id = id;
    }

    public RankingPower(Long id, String user_id, String nickname, String age, String gender, String school_grade, String school_cls, String scores, String power, String win_rate) {
        this.id = id;
        this.user_id = user_id;
        this.nickname = nickname;
        this.age = age;
        this.gender = gender;
        this.school_grade = school_grade;
        this.school_cls = school_cls;
        this.scores = scores;
        this.power = power;
        this.win_rate = win_rate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getSchool_grade() {
        return school_grade;
    }

    public void setSchool_grade(String school_grade) {
        this.school_grade = school_grade;
    }

    public String getSchool_cls() {
        return school_cls;
    }

    public void setSchool_cls(String school_cls) {
        this.school_cls = school_cls;
    }

    public String getScores() {
        return scores;
    }

    public void setScores(String scores) {
        this.scores = scores;
    }

    public String getPower() {
        return power;
    }

    public void setPower(String power) {
        this.power = power;
    }

    public String getWin_rate() {
        return win_rate;
    }

    public void setWin_rate(String win_rate) {
        this.win_rate = win_rate;
    }

}
