package com.ktfootball.www.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SIDE_AAND_B.
 */
public class SideAandB {

    private Long id;
    private String users;
    private Integer add_scores;
    private Integer result;
    private Integer goals;
    private Integer pannas;
    private Integer fouls;
    private Integer flagrant_fouls;
    private Integer panna_ko;
    private Integer abstained;
    private String users_b;
    private Integer add_scores_b;
    private Integer result_b;
    private Integer goals_b;
    private Integer pannas_b;
    private Integer fouls_b;
    private Integer flagrant_fouls_b;
    private Integer panna_ko_b;
    private Integer abstained_b;
    private String path;
    private String time;
    private Integer game_type;

    public SideAandB() {
    }

    public SideAandB(Long id) {
        this.id = id;
    }

    public SideAandB(Long id, String users, Integer add_scores, Integer result, Integer goals, Integer pannas, Integer fouls, Integer flagrant_fouls, Integer panna_ko, Integer abstained, String users_b, Integer add_scores_b, Integer result_b, Integer goals_b, Integer pannas_b, Integer fouls_b, Integer flagrant_fouls_b, Integer panna_ko_b, Integer abstained_b, String path, String time, Integer game_type) {
        this.id = id;
        this.users = users;
        this.add_scores = add_scores;
        this.result = result;
        this.goals = goals;
        this.pannas = pannas;
        this.fouls = fouls;
        this.flagrant_fouls = flagrant_fouls;
        this.panna_ko = panna_ko;
        this.abstained = abstained;
        this.users_b = users_b;
        this.add_scores_b = add_scores_b;
        this.result_b = result_b;
        this.goals_b = goals_b;
        this.pannas_b = pannas_b;
        this.fouls_b = fouls_b;
        this.flagrant_fouls_b = flagrant_fouls_b;
        this.panna_ko_b = panna_ko_b;
        this.abstained_b = abstained_b;
        this.path = path;
        this.time = time;
        this.game_type = game_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsers() {
        return users;
    }

    public void setUsers(String users) {
        this.users = users;
    }

    public Integer getAdd_scores() {
        return add_scores;
    }

    public void setAdd_scores(Integer add_scores) {
        this.add_scores = add_scores;
    }

    public Integer getResult() {
        return result;
    }

    public void setResult(Integer result) {
        this.result = result;
    }

    public Integer getGoals() {
        return goals;
    }

    public void setGoals(Integer goals) {
        this.goals = goals;
    }

    public Integer getPannas() {
        return pannas;
    }

    public void setPannas(Integer pannas) {
        this.pannas = pannas;
    }

    public Integer getFouls() {
        return fouls;
    }

    public void setFouls(Integer fouls) {
        this.fouls = fouls;
    }

    public Integer getFlagrant_fouls() {
        return flagrant_fouls;
    }

    public void setFlagrant_fouls(Integer flagrant_fouls) {
        this.flagrant_fouls = flagrant_fouls;
    }

    public Integer getPanna_ko() {
        return panna_ko;
    }

    public void setPanna_ko(Integer panna_ko) {
        this.panna_ko = panna_ko;
    }

    public Integer getAbstained() {
        return abstained;
    }

    public void setAbstained(Integer abstained) {
        this.abstained = abstained;
    }

    public String getUsers_b() {
        return users_b;
    }

    public void setUsers_b(String users_b) {
        this.users_b = users_b;
    }

    public Integer getAdd_scores_b() {
        return add_scores_b;
    }

    public void setAdd_scores_b(Integer add_scores_b) {
        this.add_scores_b = add_scores_b;
    }

    public Integer getResult_b() {
        return result_b;
    }

    public void setResult_b(Integer result_b) {
        this.result_b = result_b;
    }

    public Integer getGoals_b() {
        return goals_b;
    }

    public void setGoals_b(Integer goals_b) {
        this.goals_b = goals_b;
    }

    public Integer getPannas_b() {
        return pannas_b;
    }

    public void setPannas_b(Integer pannas_b) {
        this.pannas_b = pannas_b;
    }

    public Integer getFouls_b() {
        return fouls_b;
    }

    public void setFouls_b(Integer fouls_b) {
        this.fouls_b = fouls_b;
    }

    public Integer getFlagrant_fouls_b() {
        return flagrant_fouls_b;
    }

    public void setFlagrant_fouls_b(Integer flagrant_fouls_b) {
        this.flagrant_fouls_b = flagrant_fouls_b;
    }

    public Integer getPanna_ko_b() {
        return panna_ko_b;
    }

    public void setPanna_ko_b(Integer panna_ko_b) {
        this.panna_ko_b = panna_ko_b;
    }

    public Integer getAbstained_b() {
        return abstained_b;
    }

    public void setAbstained_b(Integer abstained_b) {
        this.abstained_b = abstained_b;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getGame_type() {
        return game_type;
    }

    public void setGame_type(Integer game_type) {
        this.game_type = game_type;
    }

}
