package com.ktfootball.www.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table UPLOAD_GYM_COURSE_RECORD.
 */
public class UploadGymCourseRecord {

    private Long id;
    private String club_id;
    private String user_id;
    private String course_combination_id;
    private String classes;
    private String is_finished;
    private String finished_time;

    public UploadGymCourseRecord() {
    }

    public UploadGymCourseRecord(Long id) {
        this.id = id;
    }

    public UploadGymCourseRecord(Long id, String club_id, String user_id, String course_combination_id, String classes, String is_finished, String finished_time) {
        this.id = id;
        this.club_id = club_id;
        this.user_id = user_id;
        this.course_combination_id = course_combination_id;
        this.classes = classes;
        this.is_finished = is_finished;
        this.finished_time = finished_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClub_id() {
        return club_id;
    }

    public void setClub_id(String club_id) {
        this.club_id = club_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getCourse_combination_id() {
        return course_combination_id;
    }

    public void setCourse_combination_id(String course_combination_id) {
        this.course_combination_id = course_combination_id;
    }

    public String getClasses() {
        return classes;
    }

    public void setClasses(String classes) {
        this.classes = classes;
    }

    public String getIs_finished() {
        return is_finished;
    }

    public void setIs_finished(String is_finished) {
        this.is_finished = is_finished;
    }

    public String getFinished_time() {
        return finished_time;
    }

    public void setFinished_time(String finished_time) {
        this.finished_time = finished_time;
    }

}
