package com.ktfootball.www.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USERS.
 */
public class Users {

    private Long id;
    private String user_id;
    private String avatar;
    private String nickname;
    private String email;
    private String phone;
    private String grade;
    private String scores;
    private String power;
    private String ktb;
    private String age;
    private String gender;

    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, String user_id, String avatar, String nickname, String email, String phone, String grade, String scores, String power, String ktb, String age, String gender) {
        this.id = id;
        this.user_id = user_id;
        this.avatar = avatar;
        this.nickname = nickname;
        this.email = email;
        this.phone = phone;
        this.grade = grade;
        this.scores = scores;
        this.power = power;
        this.ktb = ktb;
        this.age = age;
        this.gender = gender;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    public String getScores() {
        return scores;
    }

    public void setScores(String scores) {
        this.scores = scores;
    }

    public String getPower() {
        return power;
    }

    public void setPower(String power) {
        this.power = power;
    }

    public String getKtb() {
        return ktb;
    }

    public void setKtb(String ktb) {
        this.ktb = ktb;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

}
